### ISSUE TITLE
Problem with Working with Types Example from TWC wiki

### ISSUE THREAD

**Issue by jconlon** [Draccoz/potts#2]
When trying potts example from twc wiki: _Working with types._ 

Although the mixinBehaviors work, I am getting a Typescript error in Linter:
**Type 'Element' cannot be converted to type 'PaperButton'.**
    when I try to:
`const button = this.$.button as PaperButton;` as in the following code:
 

```
import { CustomElement, template } from 'twc/polymer';
import "bower:polymer/polymer-element.html";
import { PaperButton } from "bower:paper-button/paper-button.html";
import { PaperCheckedElementBehavior } from "bower:paper-behaviors/paper-checked-element-behavior.html";

@CustomElement()
@template(`<paper-button id="button">pushMe</paper-button>`)
export class MyComponent extends Polymer.mixinBehaviors([ PaperCheckedElementBehavior ], Polymer.Element) {
  constructor() {
    super();
    this.checked = true;
  }

  testButton(){
    const button = this.$.button as PaperButton;
    if (button.hasRipple()) {
      alert("Hi");
    }
  }
}
```

In another attempt I also see errors like:
**Type 'Element' cannot be converted to type 'PaperButton'.  Property 'stopKeyboardEventPropagation' is missing in type 'Element'.**

**Comment by Buslowicz** [comment]
Just published a fix, should all be fine now.
The problem was, generated classes did not extend anything. I made them all extend from `Element`, though it is still not a complete solution, as now if component A extends component B, potts will not see whats inherited from component B.
Nevertheless it works for your use case and probably plenty more :). Also please note that potts is not a full featured project, it's more of a working proof-of-concept :P.
